### ISSUE TITLE
Multi-level config into separate configs

### ISSUE THREAD

**Issue by PandaHugMonster** [PandaHugMonster/py-simputils-config#44]
Currently a file might represent a single config, and the purpose of this ticket to implement feature to store multiple independent configs within a single file/chain.

Example:
```yaml
generic-conf-1: "val-1"
generic-conf-2: "val-2"
generic-conf-3: "val-3"

module-1:
  mod-conf-1: "mod-val-1"
  mod-conf-2: "mod-val-2"
  mod-conf-3: "mod-val-3"

module-2:
  mod-conf-4: "mod-val-4"
```

With 3 different scopes/configs:
1. `root` scope including `generic-conf-1`, `generic-conf-2`, `generic-conf-3`
2. `module-1` scope
3. `module-2` scope

Where those 3 should be represented by 3 different config objects
